name: Release to npm

on:
  release:
    types: [created]

permissions:
  id-token: write
  contents: read

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/
          package-manager-cache: false
      - name: Install Dependencies
        run: npm ci
      - name: Package
        run: npm run package
      - name: Publish
        working-directory: ./packages/svader
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
